# Generated by Django 3.1.4 on 2021-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_count', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOS',
            fields=[
                ('client_os', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('report_date', models.DateField()),
            ],
            options={
                'db_table': '',
                'managed': False,
            },
        ),
    ]
